version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Central
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node-lambda
    versions:
    - 0.17.0
    - 0.18.0
    - 0.19.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
